### ISSUE TITLE
`replaceImportAddresses` does not work with inline import instances

### ISSUE THREAD

**Issue by jribbink** [onflow/flow-cadut#118]
### Instructions

Add a feature to support inline import instances such as the following:

```cadence
  pre {
      self.account.address == AddressThatNeedsToBeReplaced: "Invalid"
  }
```

### Problem

This is not currently supported by flow-cadut.  Code such as the following does not work

```javascript
const addressMap = {
  Messages: '0xf8d6e0586b0a20c7',
  OtherMessages: '0xf8d6e0586b0a20c7',
};

const code2 = `
import Messages from 0x1

transaction() {
    pre {
        self.address == Messages: "Failed" // inlined here
    }
}
`;

const replaced2 = replaceImportAddresses(code2, addressMap);
console.log({ replaced2 });
```

### Context

See original issue: #73

**Comment by MaxStalker** [comment]
What's the use case for this issue? 🤔 
I think `problem` is not outlining it correctly.

**Comment by jribbink** [comment]
I just triaged from the original without looking into it.  Now that I have, I'm not totally sure what the purpose of this is as it's more of a feature request than a cadence feature that isn't supported.
