### ISSUE TITLE
Parser couldn't parse out multi-line arguments correctly

### ISSUE THREAD

**Issue by dryruner** [onflow/flow-cadut#15]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

I've encountered the issue when using the `flow-js-testing` framework which depends on this repo. After some digging it turns out that the regex used in `extractTransactionArguments` wouldn't generate correct outputs under certain condition. (See below)

### Steps to Reproduce

Here's my transaction snippet: 
```
transaction(
    name: String,
    whole: UInt64,
    fraction: UFix64, 
) {
    // .... 
}
```

My tests fails with `Cannot read property 'startsWith' of undefined`. Debugged with some logs, it turns out that `getTemplateInfo(code)` in this [line](https://github.com/onflow/flow-cadut/blob/main/src/args.js#L199) parsed out empty args. Digging further, the regex in parser may not parse out multi-line arguments.

### Acceptance Criteria

Given multi-line arguments in transactions and scripts are common for readability, there's no harm to support this feature. 

### Context

`flow-js-testing` framework is depending on this module.

**Comment by dryruner** [comment]
Hey @MaxStalker Maksim what's your take in this issue, do you think this needs to be fixed? Thanks : )

**Comment by MaxStalker** [comment]
@dryruner absolutely! I have opened an [issue in flow-cadut repo](https://github.com/onflow/flow-cadut/issues/15) and solution is almost ready to be merged :)
You can expect this to be reflected in testing framework in next couple of days :)
