### ISSUE TITLE
Add FIND address resolver

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-cadut#33]
### Issue To Be Solved
FIND - https://test.find.xyz/ - is a third-party namespace provider allowing to resolve human readable address to Flow Address.

### Solution
- Add plugin system to `flow-cadut` to allow to provide different resolvers for arguments
- Create plugin for FIND namespace provider

**Comment by Giners** [comment]
Is this within the problem domain scope of `flow-cadut`? It seems like a cool ability to have but wouldn't someone who wanted to resolve human readable addresses to Flow addresses simply:
* Resolve addresses prior to invocation of any `flow-cadut` code
* Pass in a the resolved address via `addressMap` to the functions

**Comment by MaxStalker** [comment]
> Is this within the problem domain scope of `flow-cadut`?

Technically, everything that makes your life of a Flow developer easier is `flow-cadut` domain :)
It's also a reason, why I propose this as plugin - if you don't need this functionality, you can simply not activate it.

**Comment by Giners** [comment]
> Technically, everything that makes your life of a Flow developer easier is flow-cadut domain :)

💯 
> It's also a reason, why I propose this as plugin - if you don't need this functionality, you can simply not activate it.

👍 

Rock on. Just been more active in the community lately since Flow seems great. Just want the ecosystem to be great as well, well thought out and purposeful, and easy to use. But you are honestly already doing that. :)
