### ISSUE TITLE
Add support for arguments of Path type

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-cadut#45]
## :hand: Problem
Currently it's impossible to pass Path arguments, even though it's supported by `@onflow/types` (it was recently added).
Corresponding source code for `Path` type can be found here:
https://github.com/onflow/fcl-js/blob/master/packages/types/src/types.js#L539

## :heavy_check_mark:  Solution
- add resolver for Path type
- add tests to cover this use case

## :bulb:  Acceptance Criteria
- it should be possible to pass Path arguments
- new tests added and passing for all basic cases

## :moneybag:  Bounty
Accepted solution will be rewarded with `15 FLOW` tokens.
If you are willing to tackle it - please state your interest in the comments.

**Comment by hichana** [comment]
Hi @MaxStalker I’m interested in this issue.

**Comment by MaxStalker** [comment]
Sorry for this one - I forgot that it was already implemented here:
https://github.com/onflow/flow-cadut/blob/main/src/args.js#L168-L174

I will close this issue, but hope we will have the chance to work in the future :bow:

**Comment by hotrungnhan** [comment]
@MaxStalker  #66 add suport for public path , private path
