### ISSUE TITLE
`replaceImportAddresses` doesn't replace all instances (multiple imports / inline instances)

### ISSUE THREAD

**Issue by march213** [onflow/flow-cadut#73]
### Problem

👋🏻 Hey!

We have a cadence file where we have:
- multiple imports: `import FirstContract, SecondContract from 0xContract`
- inline instances:
  ```cdc
    pre {
        self.account.address == AddressThatNeedsToBeReplaced: "Invalid"
    }
  ```

### Steps to Reproduce

**Multiple imports example:**

```js
const addressMap = {
  Messages: '0xf8d6e0586b0a20c7',
  OtherMessages: '0xf8d6e0586b0a20c7',
};

const code = `
  import Messages, OtherMessages from 0x1
  
  pub fun main(){}
`;

const replaced = replaceImportAddresses(code, addressMap);
console.log({ replaced });
```

**Inline instances example**

```js
const addressMap = {
  Messages: '0xf8d6e0586b0a20c7',
  OtherMessages: '0xf8d6e0586b0a20c7',
};

const code2 = `
import Messages from 0x1

transaction() {
    pre {
        self.address == Messages: "Failed" // inlined here
    }
}
`;

const replaced2 = replaceImportAddresses(code2, addressMap);
console.log({ replaced2 });

```

### Acceptance Criteria

Would be nice if the `replaceImportAddresses` method would replace multiple imports and inline instances.

Is supporting this in on your roadmap ?

**Comment by MaxStalker** [comment]
Hey, @march213 👋 
- Multiple imports should be easy to fix. Thank you for flagging this 👍 
- Inline instances is a bit more tricky, unless it's something easy to tag and replace for example if it comes with `#` prefix - i.e `#MESSAGES` 🤔

**Comment by march213** [comment]
> Multiple imports should be easy to fix. Thank you for flagging this 👍

That's awesome!

> Inline instances is a bit more tricky, unless it's something easy to tag and replace for example if it comes with `#` prefix - i.e `#MESSAGES`

That potentially could work.

**Comment by jribbink** [comment]
This has been triaged into two separate issues: #117 #118
